### ISSUE TITLE
Edetabel

### ISSUE THREAD

**Issue by 4xMSAA** [4xMSAA/mastermind-game#4]
- [ ] Edetabel salvestab eelistatavalt CSV vormingus (kui on oskusi binaarsalvestamisega, pole keelatud - eeldatavasti dokumentatsioon mis kirjeldab binaarsalvestuse protsessi lühidalt)
- [ ] Edetabel hoiab skoore sõltumata objektist - objekt mis sisestatakse edetabelisse peab implementeerima endale "CompareScoreTo" meetodi, mis tagastab kas objekt 1 on üle või alla objekt 2 skoorist (väljastab tõene või väär)
- [ ] Edetabel serialiseerib oma sisu failina, ning võib oma sisu tagasi klassi laadida ka failist

Näiteline objekt mida edetabelisüsteem võiks salvestada:
https://github.com/4xMSAA/mastermind-game/blob/dev/src/main/java/scoring/Score.java

**Comment by uschaKarus** [comment]
package kehtnakhkta18;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
/**
 *
 * @author uko.karus
 */
public class Scoreboard {
    public static void main(String[] args) {
  try (PrintWriter writer = new PrintWriter(new File("score.csv"))) {
      Scanner myObj = new Scanner(System.in);  
    System.out.println("Enter username");

    String userName = myObj.nextLine();  
    
      StringBuilder sb = new StringBuilder();
      sb.append("Name: " + userName);
      sb.append(',');
      sb.append("Turns: " + "*Turns*");
      sb.append(',');
      sb.append("Time: " + "*time*");
      sb.append('\n');

      writer.write(sb.toString());

    } catch (FileNotFoundException e) {
      System.out.println(e.getMessage());
    }

}
}
midagi säärast?

**Comment by 4xMSAA** [comment]
See ei täida 2. punkti
+  Edetabel hoiab skoore sõltumata objektist - objekt mis sisestatakse edetabelisse peab implementeerima endale "CompareScoreTo" meetodi, mis tagastab kas objekt 1 on üle või alla objekt 2 skoorist (väljastab tõene või väär)

Hetkel hoiab edetabel **teatud vormingut** - mis siis kui vorming skoori hoidmiseks muutub?

**Comment by matisroo** [comment]
package kehtnakhkta18;

import java.io.*;
import java.nio.charset.Charset;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.time.Duration;
import java.time.Instant;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.Collectors;


public final class App {
    private App() {
    }

    /**
     * @param args The arguments of the program.
     */
    public static void main(String[] args) {
        Scanner myObj = new Scanner(System.in);
        System.out.println("Sisestage Kasutajanimi");

        String userName = myObj.nextLine();
        String turns = null;

        Instant start = Instant.now();
        //Timeunit.seconds.sleep(5);
        Instant end = Instant.now();
        Duration interval = Duration.between(start, end);


        // Teeb 'path' .csv faili
        Path p = Paths.get("C://Skoor.csv");
        // Teeb US-ASCII Charset
        Charset c = Charset.forName("US-ASCII");
        // String'id mida loetakse
        String line0 = "-------------------------";
        String line1 = "Kasutajanimi: " + userName;
        String line2 = "Käike: " + turns;
        String line3 = "Aeg: " + interval.getSeconds();
        String line4 = "Skoor: " + "694201337";
        String line5 = "-------------------------";
        // konvertib texti Array'sse ja salvestab stringi listina
        List<String> lines = Arrays.asList(line0, line1, line2, line3, line4, line5);
        try {
            // kirjutab ridasi failist
            Path write = Files.write(p, lines, c);
        } catch (IOException e) {
            System.err.println(e);
        }
        List<String> read = null;
        try {
            // Loeb Read Faili
            read = Files.readAllLines(p, c);
        } catch (IOException e) {
            e.printStackTrace();
        }
        // 'iterates' listi peale ja printib
        for (String content : read) {
            System.out.println(content);
        }
    }
}
